# Definie o nome da pipeline
name: CI Post-it App

# Evento que vai disparar o Job
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
# Testes Unitarios                                                              #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
  job1:
    name: Unit Tests
    runs-on: ubuntu-latest

    # Checkout código fonte
    steps:
    - uses: actions/checkout@v2

    # Instalação Python3
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    # Cria virtual env Python
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    # Instalação de Módulos que são necessários para a Aplicação. 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Executa scripts de teste (PyTest, Django test suites, etc.)
    - name: Execute tests
      run: |
        pip install pytest
        pip install pytest-cov
        pip install coverage
        coverage run test_core.py 
        coverage report app.py
        coverage xml app.py
      
    # Checkin código fonte
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/

###-- END Job1 ---###

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
# Teste de Qualidade SonarCloud                                                 #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
  job2:
    name: Quality Test SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

###-- END Job2 ---###

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
# Deploy em Homologação (Heroku)                                                #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#

  job3:
    name: Staging Deploy
    runs-on: ubuntu-latest
    needs: [job1, job2]
    environment:
      name: 'staging'

    steps:
      # Download package app
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      # Deploy Heroku    
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "post-it-devopslab"
          heroku_email: "santos.pedroh@gmail.com"
          procfile: "web: gunicorn app:app"

###-- END Job3 ---###

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
# Testing em Homologação                                                        #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------# 

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
    # curl na rota /. Method GET na URL de homologação
    - name: curl
      uses: wei/curl@master
      with:
        args: -I https://post-it-devopslab.herokuapp.com

    # curl na rota /salvar. Method POST na URL de homologação
    - name: curl
      uses: wei/curl@master
      with:
        args: -X POST -F 'nome=Robot CI' -F 'mensagem=Teste de formulario CI' https://post-it-devopslab.herokuapp.com/salvar

###-- END Job4 ---###

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
# Deploy em Produção (Azure)                                                    #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------# 
  job5:
    name: Production Deploy
    runs-on: ubuntu-latest
    needs: [job3, job4]
    environment:
      name: 'production'

    steps:
      # Download package app
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
        
      # Deploy Azure
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'post-it-devopslab'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_655d664b564740e3af7471bc9651d3ec }}

###-- END Job4 ---###

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
# Testing em Produção                                                           #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------# 
  job6:
      runs-on: ubuntu-latest
      steps:
      # curl method GET na URL de homologação
      - name: curl
        uses: wei/curl@v1
        with:
          args: -I https://post-it-devopslab.azurewebsites.net
